  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Episodes"
  weight = 200
  identifier = "episodes"
  url = "/post/"

  [[main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Support"
  weight = 400
  identifier = "support"
  url = "/support/"

   [[main]]
  name = "Subscribe"
  weight = 500
  identifier = "subscribe"
  url = "/subscribe/"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "Privacy"
  weight = 1
  identifier = "privacy"
  url = "/imprint/"