  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Donate"
  weight = 400
  identifier = "donate"
  url = "https://buymeacoffee.com"

   [[main]]
  name = "Subscribe"
  weight = 500
  identifier = "subscribe"
  url = "/subscribe/"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "Privacy"
  weight = 1
  identifier = "privacy"
  url = "/imprint/"